comment:
  image:
    repository: otusdevops77/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: otusdevops77/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: otusdevops77/ui
    tag: latest
    service:
      externalPort: 9292
