FROM alpine:3.7


RUN apk update && \
    apk upgrade && \
    apk --no-cache add curl wget bash && \
    apk --no-cache add ruby ruby-bundler ruby-io-console curl-dev ruby-dev build-base && \
    rm -rf /var/cache/apk/*


ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
