global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ilya_nikolskiy'
