version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
      - back_net
      - front_net
  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}/tcp
    networks:
      - reddit
      - front_net
  post:
    image: ${USERNAME}/post:latest
    networks:
      - reddit
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:latest
    networks:
      - reddit
      - front_net
      - back_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:
networks:
  reddit:
  front_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${FRONT_SUBNET}
  back_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.2.0/24
