version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
      - back_net
      - front_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}/tcp
    networks:
      - reddit
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - reddit
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - reddit
      - front_net
      - back_net
volumes:
  post_db:

networks:
  reddit:
  front_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${FRONT_SUBNET}
  back_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.2.0/24
