concurrent = 10
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "scaling-runner"
  url = "http://35.233.22.187/"
  token = "23c589d910a8e916350cea334dc887"
  executor = "docker+machine"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.machine]
    IdleCount = 0
    IdleTime = 600
    MachineDriver = "google"
    MachineName = "scale-runner"
    OffPeakTimezone = ""
    OffPeakIdleCount = 0
    OffPeakIdleTime = 0
    MachineOptions = [
      "google-project=XXXXXXXXXXXXXXXXXXXXXXXXX",
      "google-machine-type=n1-standard-1",

